name: Prueba self-hosted runner

on:
  push:

jobs:
  comprobar-tokens:
    runs-on: self-hosted

    steps:
      - name: Comparar tokens
        shell: powershell
        env:
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
        run: |
          $localToken = [Environment]::GetEnvironmentVariable("LOCAL_DEV_TOKEN", "User")

          if ($env:DEV_TOKEN -eq $localToken) {
              Write-Host "Los tokens coinciden"
          }
          else {
              Write-Host "Los tokens NO coinciden"
              exit 1
          } 